functional: 
- пользователь должен иметь возможность искать товары по ключевому слову или категории
- пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
- пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
- пользователь имеет возможность зарегистрироваться на сайте
- пользователь имеет возможность авторизоваться на сайте
non-functional:
- веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- сайт должен быть безопасным и защищать данные пользователя
- сайт должен иметь мобильную версию
- сайт должен быть протестирован на совместимость с последними версиями браузеров
- сайт должен быть способен обрабатывать большое количество трафика
- сайт должен быть доступен на различных устройствах
implicit:
- пользователь имеет возможность выбрать язык 
- пользователь имеет возможность выбрать способ оплаты товара
- пользователь может оплатить товар на сайте
- пользователь имеет возможность привязать свою банковскю карту 
- пользватель имеет возможность удалить товар из корзины
- пользователь имеет возможность отменить свой заказ до того,как он был отправлен 
- пользователь имеет возможность выбрать город доставки товара 
- пользователь имеет возможность выбрать бренд товара
